---
abstract: 'Modules for handling RDF data within the Catmandu framework'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.8, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-RDF
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.9'
  RDF::NS: '20140910'
  RDF::Trine: '1.0'
  RDF::aREF: '0.18'
resources:
  bugtracker: https://github.com/gbv/Catmandu-RDF/issues
  homepage: https://github.com/gbv/Catmandu-RDF
  repository: https://github.com/gbv/Catmandu-RDF.git
version: '0.18'
x_contributors:
  - 'Jakob Voss <voss@gbv.de>'
